import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GoFGast Wish",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
   
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
        <html lang="en">
          <body
            className={`${inter.className} antialiased`}
          >
            <NuqsAdapter>
              <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
              <Toaster />
              {children}
            </NuqsAdapter>
             
          </body>
        </html>
      </TRPCReactProvider>
   
  );
}
